CREATE TABLE pokemon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    sprite_url VARCHAR(2048),
    category VARCHAR(255),
    mass INT NOT NULL,
    local_name VARCHAR(255) NOT NULL,
    region VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_pokemon_external_id UNIQUE (external_id)
);

CREATE TABLE pokemon_ability (
    pokemon_id BIGINT NOT NULL,
    ability VARCHAR(255) NOT NULL,
    position INT NOT NULL,
    CONSTRAINT fk_pokemon_ability_pokemon FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE
);

CREATE TABLE pokemon_internal_tag (
    pokemon_id BIGINT NOT NULL,
    tag VARCHAR(255) NOT NULL,
    position INT NOT NULL,
    CONSTRAINT fk_pokemon_internal_tag_pokemon FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE
);

CREATE INDEX idx_pokemon_ability_pokemon_id ON pokemon_ability (pokemon_id);
CREATE INDEX idx_pokemon_internal_tag_pokemon_id ON pokemon_internal_tag (pokemon_id);
